### ISSUE TITLE
A couple of oddities

### ISSUE THREAD

**Issue by zzedmore** [amigavision/AmigaVision#101]
A quick question/bug report.

There are two entries for 'Bard's Tale'. A normal one and the other is noted as (OCS). Is this an error ?

Also, there are two entries for 'Cabal'. The one listed as (OCS) is the game 'Shootout'.

'Formula 1 Grand Prix' (Cirrus) has the same screenshot as 'Formula One Grand Prix' (Microprose).

Just a suggestion, the original versions of 'Eye of the Beholder 1 & 2' have (OCS) in the filename. Wouldn't it be better to remove the (OCS) and add (AGA) to the enhanced versions instead ?

Keep up the great work on this collection. Looking forward to the new version !

**Comment by Optiroc** [comment]
Thanks for the report!

The Cabal/Shootout mixup was some freak accident, that I happened on and fixed just recently. I'll see what's up with Bard's Tale.

As for Eye of the Beholder: I agree. It turns out that way automatically, because reasons... :) I'll see if it can be fixed.

TODO:
- [ ] Bards Tale / Bards Tale OCS
- [ ] 'Formula 1 Grand Prix' (Cirrus) has the same screenshot as 'Formula One Grand Prix' (Microprose)
- [ ] Eye of the Beholder: Render OCS version without hardware specifier
