### ISSUE TITLE
Add "Napalm" with patch

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#106]
The game "Napalm" — which we don't have a configuration for at the moment, since it was originally targeted to RTG Amigas and seemed unplayably slow on an AGA Amiga — seems to work well if you patch in the chunky-to-planar pixel support:

https://www.youtube.com/watch?v=yiPkbL4wObI

The patch is here:
http://aminet.net/package/util/boot/Blazewcp

(I don't have any strong attachment to this game, but probably worth taking a quick look)

**Comment by Optiroc** [comment]
I'm a bit hesitant to experiment with system wide patches like BlazeWCP. There used to be a couple similar patches included in the startup sequence (FBlit and FText), but they didn't play nicely with some games.

**Comment by limi** [comment]
Yes, understood. FWIW, this seems extremely narrowly focused, only changes the execution speed of those three function calls, not the functionality itself. It’s commonly included in other Amiga game setups, but we could also leave it as an exercise for the reader.

(it should of course only be called in this particular game setup, but there’s a theoretical risk that it would affect anything launched after exiting that game)

**Comment by Optiroc** [comment]
As far as I can tell BlazeWCP, in contrast to FBlit an FText, doesn't have an option to restore the original OS functions. But we can apply it upon loading specific titles.. There are many other things (demos in particular) that can leave the system in a somewhat weird state after exiting, so that's fair game I think.

There's one good reason to put Napalm in, I think: It's included in the "EAB Top Exclusives" list, where it is currently displayed as "not available". So why not!

**Comment by Optiroc** [comment]
Well, this is a CD game that apparently requires the CD to be mounted to boot. If someone has a "no CD" patch we could include it.

**Comment by Optiroc** [comment]
I fooled around with Napalm (and Genetic Species which is the other "not available" title) for a bit. Will not touch again.

**Comment by Optiroc** [comment]
Also, the platforms we’re targeting are not what these games were made for (ideally 060 with RTG and AHI sound). Closing.
