### ISSUE TITLE
WINGS OF DEATH - "PAL" Game running in "NTSC" mode !!! 

### ISSUE THREAD

**Issue by Turricaner** [amigavision/AmigaVision#120]
WINGS OF DEATH - is crashing on exit.
This is because it is running in "NTSC" mode  and not 
in "PAL" mode like in the description in the Further Info Box.
After the correction everything is fine.

**Comment by limi** [comment]
Thanks for that info! Since the game is an Atari ST port, it needs to run in NTSC (what we call “PAL60” in this case), so we don’t want to switch it over to PAL and have the graphics be in the wrong aspect ratio.

Probably worth filing a bug upstream, so I did:
http://mantis.whdload.de/view.php?id=6251

**Comment by Turricaner** [comment]
Ok, didn't know about PAL60 and the resulting aspect ratio.
By the way ... great work !

**Comment by Turricaner** [comment]
OK - But where do you want to release the December update ? (last one doesen´t exists any more on archive.org)

**Comment by rsn8887** [comment]
Just because it is an Atari ST mode doesn't mean it should run in PAL60.

This game is a German production and should run in PAL.
