### ISSUE TITLE
[MiSTer] [2023.12.25] [1080p] [Virocop] 5xPAL scaling causes lives and ammo counter to be left off the bottom of the screen.

### ISSUE THREAD

**Issue by IainMcNulty** [amigavision/AmigaVision#150]
On MiSTer (1080p) - 5xPAL scaling causes lives and ammo counter to be left off the bottom of the screen on Virocop.

Here's what we see on the current version of Mega AGS/AmigaVision using the included scaling settings:
![My Great Capture Screenshot 2024-01-04 00-15-30](https://github.com/amigavision/AmigaVision/assets/58012852/f8d5b362-2c57-45f0-95aa-8744cc44bd6c)

And here's what the same game looks like with the ammo and lives counters visible:
![My Great Capture Screenshot 2024-01-04 00-14-14](https://github.com/amigavision/AmigaVision/assets/58012852/f75285b7-adcf-4d3d-8cff-4e4471fa1265)

This makes the title incredibly difficult to play as the player cannot tell how much ammo is remaining on limited ammo weapons.

**Comment by limi** [comment]
I *think* I managed to find a good compromise between 5× crop and showing the energy/ammo meters — but Virocop is one of those games I never got around to playing seriously, so I’d appreciate your feedback.

If you want to test the new setting on your current setup:

Edit `Amiga:AGS2/Run/Game/Virocop (AGA)[en]`

Change the `vadjust` line to:

`ags-vadjust s=5 v=24 h=0`

Let me know if this seems acceptable. It crops a little bit of the score and number of lives along the top, but seems worth it to get 5× scale, since they are still readable.

**Comment by IainMcNulty** [comment]
These settings are far better, I would consider this an appropriate fix.

As a heads-up, the number up top isn't number of lives, it is viruses remaining in the level for Virocop to eliminate, the lives counter is in the bottom-left corner of the screen 😉

**Comment by limi** [comment]
> These settings are far better, I would consider this an appropriate fix.
> 
> As a heads-up, the number up top isn't number of lives, it is viruses remaining in the level for Virocop to eliminate, the lives counter is in the bottom-left corner of the screen 😉

Ah! As long as it is still reasonably readable — which it should be — I’ll consider this fixed.
