### ISSUE TITLE
First Samurai slightly cropped at the bottom on iPad screen

### ISSUE THREAD

**Issue by keungk** [amigavision/AmigaVision#156]
![20240119_215245-screen](https://github.com/amigavision/AmigaVision/assets/2817123/bece70ea-012a-441d-b93b-d1e9a6b108a9)

**Comment by limi** [comment]
The offsets should not be applied on the iPad screens, so not sure how that can happen. Maybe the game’s default settings are very off. That being said, we had the wrong offset for 5×PAL here, I have adjusted it so that the HUD is visible now.

Whether this would fix the iPad screen issue, I don’t know.
