### ISSUE TITLE
Shipping might be done with only Amiga.cfg, not minimig.cfg?

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#81]
I have several friends who destroyed their own personal startup config by copying over the AmigaVision minimig.cfg over their own.

Many Amiga users have personal configs, using their own old hdf images from back in the day. It is disruptive to have an AmigaVision install just wipe such a config completely by overwriting minimig.cfg.

Since the isolation between AmigaVision configs and personal configs works pretty well already, it might be good to not ship AmigaVision with a "minimig.cfg". It already comes with Amiga.cfg and the corresponding Amiga.mgl, which might be enough? Amiga.cfg could even be renamed AmigaVision.cfg and then AmigaVision could live happily besides personal configurations.

I am just writing down my thoughts for suggestions, please feel free to ignore.

**Comment by limi** [comment]
So, first off: this has been the case with every MegaAGS release from the start; if you blindly copy over the files if you have a custom setup, you would always kill your setup.

That, of course, doesn’t mean you are wrong — we debated this a bit back and forth, and erred on the side of supporting people that didn’t read the docs, just copied over everything and launched Minimig.

Now that we have the new MGL setup, I agree that we should probably not touch Minimig at all, and just ship everything inside the `Amiga.mgl` setup.

We are going to issue a quick follow-up “patch” release for the 2023.04.05 release (as we always end up doing since there’s always a couple of issues discovered on release), and we will stop shipping anything related to the Minimig config at all from then on.

I personally am pretty strongly against shipping an entry called `AmigaVision.mgl`, though — we are trying to appeal to the people that “just want to try Amiga games”, and it’s nice to have a clean, understandable name without involving the branding of our project in that list. (I will update the docs to point out the possibility of duplicate entries if you use `names.txt`, though :)
